### ISSUE TITLE
fails to build with hickory 0.25

### ISSUE THREAD

**Issue by daniel-baumann** [icann/icann-rdap#210]
Hi,

Debian is moving to moving to hickory 0.25 which makes icann-rdap-cli fail to build:

```
error[E0432]: unresolved imports `hickory_client::client::AsyncClient`, `hickory_client::client::ClientConnection`, `hickory_client::error::ClientError`, `hickory_client::rr`, `hickory_client::udp`
  --> src/rt/exec.rs:17:18
   |
17 |         client::{AsyncClient, ClientConnection, ClientHandle},
   |                  ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^ no `ClientConnection` in `client`
   |                  |
   |                  no `AsyncClient` in `client`
18 |         error::ClientError,
   |         ^^^^^^^^^^^^^^^^^^ no `ClientError` in `error`
19 |         proto::error::ProtoError,
20 |         rr::{DNSClass, Name, RecordType},
   |         ^^ could not find `rr` in `hickory_client`
21 |         udp::UdpClientConnection,
   |         ^^^ could not find `udp` in `hickory_client`
   |
   = help: consider importing this struct instead:
           hickory_client::ClientError

error[E0603]: module `error` is private
   --> src/rt/exec.rs:18:9
    |
 18 |         error::ClientError,
    |         ^^^^^ private module
    |
note: the module `error` is defined here
   --> /usr/share/cargo/registry/hickory-client-0.25.2/src/lib.rs:143:1
    |
143 | mod error;
    | ^^^^^^^^^

error[E0603]: module `error` is private
  --> src/rt/exec.rs:19:16
   |
19 |         proto::error::ProtoError,
   |                ^^^^^ private module
   |
note: the module `error` is defined here
  --> /usr/share/cargo/registry/hickory-proto-0.25.2/src/lib.rs:57:1
   |
57 | mod error;
   | ^^^^^^^^^

error[E0282]: type annotations needed for `(_, _)`
   --> src/rt/exec.rs:351:9
    |
351 |     let (mut client, bg) = AsyncClient::connect(conn).await?;
    |         ^^^^^^^^^^^^^^^^
...
359 |     let query = client.query(Name::from_str(host)?, DNSClass::IN, RecordType::A);
    |                 ------ type must be known at this point
    |
help: consider giving this pattern a type, where the placeholders `_` are specified
    |
351 |     let (mut client, bg): (_, _) = AsyncClient::connect(conn).await?;
    |                         ++++++++

error[E0282]: type annotations needed
   --> src/rt/exec.rs:362:9
    |
362 |     let response = query.await?;
    |         ^^^^^^^^
363 |
364 |     for answer in response.answers() {
    |                   -------- type must be known at this point
    |
help: consider giving `response` an explicit type
    |
362 |     let response: /* Type */ = query.await?;
    |                 ++++++++++++

error[E0282]: type annotations needed
   --> src/rt/exec.rs:365:15
    |
365 |         match answer.record_type() {
    |               ^^^^^^ cannot infer type

error[E0282]: type annotations needed
   --> src/rt/exec.rs:399:9
    |
399 |     let response = query.await?;
    |         ^^^^^^^^
400 |
401 |     for answer in response.answers() {
    |                   -------- type must be known at this point
    |
help: consider giving `response` an explicit type
    |
399 |     let response: /* Type */ = query.await?;
    |                 ++++++++++++

error[E0282]: type annotations needed
   --> src/rt/exec.rs:402:15
    |
402 |         match answer.record_type() {
    |               ^^^^^^ cannot infer type

Some errors have detailed explanations: E0282, E0432, E0603.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `icann-rdap-cli` (lib) due to 8 previous errors
```

Regards,
Daniel

**Comment by anewton1998** [comment]
I was just looking at necessary dependency upgrades yesterday, and this is one that is on my list.

**Comment by anewton1998** [comment]
Code is now in dev, along with all other dependency upgrades (everything should be up to date).
Pending 0.0.29 release.... which either happens tomorrow or two weeks from today depending on my schedule.

**Comment by daniel-baumann** [comment]
great, thanks!

**Comment by anewton1998** [comment]
Released in #211 v0.0.29.
